global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'webhook'
  routes:
  - match:
      serverity: critical
receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://alert-webhook-dingtalk:8060/dingtalk/webhook01/send'
