apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnYWxlcnRuYW1lJywgJ2NsdXN0ZXInLCAnc2VydmljZSddCiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiAxMmgKICByZWNlaXZlcjogJ3dlYmhvb2snCiAgcm91dGVzOgogIC0gbWF0Y2g6CiAgICAgIHNlcnZlcml0eTogY3JpdGljYWwKcmVjZWl2ZXJzOgotIG5hbWU6ICd3ZWJob29rJwogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogJ2h0dHA6Ly9hbGVydC13ZWJob29rLWRpbmd0YWxrOjgwNjAvZGluZ3RhbGsvd2ViaG9vazAxL3NlbmQnCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
